export const MAP_MIN_ZOOM = 7;
export const INACCESSIBLE_ROAD_SECTION_COLOR = '#FE5000';
export const INACCESSIBLE_CARRIAGEWAY_TYPE_COLOR = '#0056A4';
export const ACCESSIBLE_ROAD_SECTION_COLOR = '#07A029';
